source 'https://rubygems.org'
source 'https://gem.fury.io/engineerai'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
gem 'redis'
gem 'redis-namespace'
gem 'redis-rails'
gem "sidekiq-cron"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'figaro'
  gem 'simplecov', '0.18.0'
end

group :development do
  gem 'dotenv-rails'
  gem 'pry'
  gem 'letter_opener'
end

group :test do
  gem 'rspec-rails'
  gem 'database_cleaner-active_record'
  gem 'shoulda-matchers'
  gem 'factory_bot_rails'
  gem 'database_cleaner-active_record'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_catalogue-0e5da613', '0.0.3', require: 'bx_block_catalogue'
gem 'bx_block_categories-acd0763f', '0.0.4', require: 'bx_block_categories'
gem 'bx_block_data_import_export_csv-ec567cbb', '0.0.1', require: 'bx_block_data_import_export_csv'
gem 'bx_block_push_notifications-c0f9e9b7', '0.0.2', require: 'bx_block_push_notifications'
gem 'bx_block_shopping_cart-9ec30a1c', '0.0.1', require: 'bx_block_shopping_cart'
gem 'account_block', '0.0.21'
gem 'bx_block_roles_permissions-c50949d0', '0.0.5', require: 'bx_block_roles_permissions'
gem 'bx_block_admin', '0.0.8'
gem 'bx_block_appointment_management-eb816fd3', '0.0.5', require: 'bx_block_appointment_management'
gem 'bx_block_scheduling-d1f08754', '0.0.1', require: 'bx_block_scheduling'
gem 'bx_block_notifications-a22eb801', '0.0.2', require: 'bx_block_notifications'
gem 'bx_block_automatic_renewals-0b2de503', '0.0.2', require: 'bx_block_automatic_renewals'
gem 'bx_block_login-3d0582b5', '0.0.6', require: 'bx_block_login'
gem 'bx_block_forgot_password-4de8968b', '0.0.5', require: 'bx_block_forgot_password'
gem 'builder_base', '0.0.39'
gem 'sassc-rails'
gem 'activeadmin'
gem 'arctic_admin'
gem 'activeadmin_addons'
gem 'active_admin_role'
gem 'activeadmin_json_editor'
gem 'active_admin_datetimepicker'
gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'
gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'
gem 'week_of_month'
gem "aws-sdk-s3", require: false
gem 'ckeditor'
gem 'fcm'
gem 'pagy', '~> 3.5'
gem 'whenever'
gem "chartkick", '~> 3.0.2'
gem "groupdate"
gem 'ransack'
gem 'stripe-rails'
gem 'twilio-ruby'
gem 'paypal-sdk-rest'
