source 'https://rubygems.org'
source 'https://gem.fury.io/engineerai'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
gem 'image_processing', '~> 1.2'
gem 'active_storage_base64'
gem 'activestorage-validator'
gem 'active_storage_validations'
gem 'file_validators'


# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '5.1.2'
  gem 'rspec-sonarqube-formatter', '1.5.0'
  gem 'simplecov', '0.17'
  gem 'simplecov-json', :require => false
  gem 'factory_bot'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'faker', '~> 2.16'
  gem "factory_bot_rails"
  gem 'shoulda-matchers', '~> 4.0'
end

group :development do
  gem 'dotenv-rails'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-doc'
end

group :test do
  gem 'rspec-sidekiq'
  gem 'webmock'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_events', '0.0.1'
gem 'bx_block_search', '0.1.4'
gem 'bx_block_push_notifications-c0f9e9b7', '0.0.10', require: 'bx_block_push_notifications'
gem 'bx_block_roles_permissions-c50949d0', '0.0.6', require: 'bx_block_roles_permissions'
gem 'bx_block_posts-3dc5b993', '0.0.12', require: 'bx_block_posts'
gem 'bx_block_profile', '0.0.8', require: 'bx_block_profile'
gem 'bx_block_profile_bio', '0.1.6'
gem 'bx_block_stripe_integration', '0.1.6'
gem 'bx_block_location-99004202', '0.0.4', require: 'bx_block_location'
gem 'bx_block_notifications-a22eb801', '0.0.5', require: 'bx_block_notifications'
gem 'bx_block_admin', '0.0.12'
gem 'bx_block_feature_settings', '0.1.0'
gem 'bx_block_login-3d0582b5', '0.0.10', require: 'bx_block_login'
gem 'bx_block_forgot_password-4de8968b', '0.0.6', require: 'bx_block_forgot_password'
gem 'bx_block_phone_verification', '0.0.2'
gem 'bx_block_categories-acd0763f', '0.0.9', require: 'bx_block_categories'
gem 'builder_base', '0.0.45'
gem 'sassc-rails'
gem 'activeadmin'
gem 'active_admin_role'
gem 'activeadmin_json_editor'
gem 'active_admin_datetimepicker'
gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'
gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'
gem 'bx_block_cors'
gem 'rack-cors'
gem 'pry'
gem 'activeadmin_quill_editor'
gem 'rails-i18n', '~> 7.0.0' # For 7.0.0
gem 'money-rails', '~>1.12'
gem "rspec", "~> 3.12"
gem 'geocoder'
gem 'pg_search'
gem "mini_magick"
gem 'twilio-ruby'
gem 'redis', '~> 4.8.0'
